version: "3.8"
services:
  food-app-ui:
    image: food-delivery-ui:1.0.3
    ports:
     - "80:80"
  inventorydb:
    image: food-delivery-db:1.0.0
    ports:
     - "5432:5432"
  inventoryservice:
    image: inventory-service:1.0.4
    environment:
      - DB_HOST=inventorydb
    ports:
     - "3001:3001"
    depends_on:
     - inventorydb