apiVersion: v1
kind: Service
metadata:
  name: food-delivery-ui
spec:
  selector:
     app: food-delivery
     kind: front-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer